# Quickstart for GitHub Actions
# https://docs.github.com/en/actions/quickstart

name: CI
on: [ push, pull_request, workflow_dispatch ]
jobs:
  test:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    name: Test on JDK ${{ matrix.java }} OS ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        java: [ 8, 11, 17, 21, 24 ]
      fail-fast: false
      max-parallel: 64

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Run dev mode test
        run: ./mvnw -V --no-transfer-progress clean package
        if: matrix.java != 17
      - name: Run release mode test
        run: ./mvnw -V --no-transfer-progress clean package spotbugs:check git-commit-id:validateRevision -DperformRelease -P'!enforce-project-version-when-release'
        if: matrix.java == 17
      # https://github.com/marketplace/actions/codecov
      - uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Check forbidden classes
        run: scripts/check-forbidden-classes.sh
        # https://docs.github.com/en/actions/learn-github-actions/variables#detecting-the-operating-system
        if: runner.os != 'Windows'
      # https://remarkablemark.org/blog/2017/10/12/check-git-dirty/
      - name: Check git dirty
        run: |
          git status --short
          [ -z "$(git status --short)" ]
        if: runner.os != 'Windows'
